### ISSUE TITLE
Production deployment job runs even when checks fail

### ISSUE THREAD

**Issue by taesungh** [HackAtUCI/irvinehacks-site#234]
Our latest commit to main (418f919) was still deployed to production even though unit tests failed. This should not be allowed since that risks deploying a potentially broken application (assuming our unit tests/checks workflows are correct).

This seems to be because our `deploy-prod` workflow depends only on completion of rather than a specific outcome of the `run-checks` workflow as described in community/community#26238. We'll need check the workflow conclusion to conditionally run the jobs, something like the following:
```yaml
jobs:
  <job-name>:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    ...
```
